### ISSUE TITLE
Failed to assign new IDs to computers and peripherals

### ISSUE THREAD

**Issue by mzuletal** [cc-tweaked/CC-Tweaked#1030]
### Minecraft Version

1.16.x

### Version

1.100.2

### Details

When trying to start a computer without an ID assigned, computer remains shut down and gives a log error in server console. This issue also happens when trying to use a wired modem next to a peripheral.

These are the logs for whwen trying to use the computer. https://pastebin.com/mXzhCg2u

These ones are when trying to use the wired modem. https://pastebin.com/8EXHUGPs

**Comment by SquidDev** [comment]
<details><summary>Stacktrace for easier reading</summary>

```
[ComputerCraft-Computer-Runner-0/ERROR] [computercraft/]: Error running task on computer #-1
java.lang.NullPointerException: null
        at dan200.computercraft.shared.util.IDAssigner.getNextId(IDAssigner.java:90) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.ComputerCraftAPIImpl.createUniqueNumberedSaveDir(ComputerCraftAPIImpl.java:86) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.api.ComputerCraftAPI.createUniqueNumberedSaveDir(ComputerCraftAPI.java:69) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.shared.computer.core.ServerComputer.assignNewID(ServerComputer.java:356) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.core.computer.Computer.assignID(Computer.java:142) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.core.computer.ComputerExecutor.getRootMount(ComputerExecutor.java:350) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.core.computer.ComputerExecutor.createFileSystem(ComputerExecutor.java:362) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.core.computer.ComputerExecutor.turnOn(ComputerExecutor.java:436) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.core.computer.ComputerExecutor.work(ComputerExecutor.java:590) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.core.computer.ComputerThread$TaskRunner.run(ComputerThread.java:504) [computercraft:1.100.2] {re:classloading}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}
```

<details>

Would you be able to paste the contents of your `computercraft/ids.json` file here? You can probably delete it afterwards, and it _should_ fix things.

**Comment by mzuletal** [comment]
The json its empty....... should i delete it and restart the server?

**Comment by SquidDev** [comment]
Yes.

**Comment by mzuletal** [comment]
Deleting it and restarting the server fixed it, appreciate the help.

**Comment by SquidDev** [comment]
Re-opening this - probably some better error handling we could do here.
