### ISSUE TITLE
Server crash on player connect (java.lang.NoClassDefFoundError: dan200/computercraft/shared/command/UserLevel$1

### ISSUE THREAD

**Issue by s-sx-x** [cc-tweaked/CC-Tweaked#1043]
### Minecraft Version

1.16.x

### Version

1.100.2 (MC/forge 1.16.5)

### Details

Has occured on multiple independent world saves for me. Can't really make any sense of it based on the source.

`java.lang.NoClassDefFoundError: dan200/computercraft/shared/command/UserLevel$1
        at dan200.computercraft.shared.command.UserLevel.toLevel(UserLevel.java:42) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.shared.command.UserLevel.test(UserLevel.java:61) ~[computercraft:1.100.2] {re:classloading}
        at dan200.computercraft.shared.command.UserLevel.test(UserLevel.java:18) ~[computercraft:1.100.2] {re:classloading}
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[?:?] {re:classloading}
        at net.minecraft.command.Commands.func_197052_a(Commands.java:279) ~[?:?] {re:classloading}
        at net.minecraft.command.Commands.func_197052_a(Commands.java:305) ~[?:?] {re:classloading}
        at net.minecraft.command.Commands.func_197051_a(Commands.java:273) ~[?:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:598) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:492) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:classloading}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:classloading}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.shared.command.UserLevel$1
        at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
        ... 20 more
        Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for dan200.computercraft.shared.command.UserLevel$1
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
                at dan200.computercraft.shared.command.UserLevel.toLevel(UserLevel.java:42) ~[computercraft:1.100.2] {re:classloading}
                at dan200.computercraft.shared.command.UserLevel.test(UserLevel.java:61) ~[computercraft:1.100.2] {re:classloading}
                at dan200.computercraft.shared.command.UserLevel.test(UserLevel.java:18) ~[computercraft:1.100.2] {re:classloading}
                at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[?:?] {re:classloading}
                at net.minecraft.command.Commands.func_197052_a(Commands.java:279) ~[?:?] {re:classloading}
                at net.minecraft.command.Commands.func_197052_a(Commands.java:305) ~[?:?] {re:classloading}
                at net.minecraft.command.Commands.func_197051_a(Commands.java:273) ~[?:?] {re:classloading}
                at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:598) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
                at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:492) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
                at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
                at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:classloading}
                at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:classloading}
                at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
                at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
                at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
                at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
                at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
                at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
                at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
                at java.lang.Thread.run(Thread.java:829) [?:?] {}
        Caused by: java.nio.channels.ClosedChannelException
                at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150) ~[?:?] {}
                at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:349) ~[?:?] {}
                at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:52) ~[?:?] {}
                at jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:970) ~[jdk.zipfs:?] {}
                at jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:963) ~[jdk.zipfs:?] {}
                at jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:1777) ~[jdk.zipfs:?] {}
                at jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:1715) ~[jdk.zipfs:?] {}
                at jdk.nio.zipfs.ZipFileSystem$3.fill(ZipFileSystem.java:1662) ~[jdk.zipfs:?] {}
                at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:252) ~[modlauncher-8.0.9.jar:?] {}
                ... 23 more`

**Comment by s-sx-x** [comment]
Seems to be happening regulary with every fresh world.

Dont't rly have anything in that world except for a GPS anchor, an advance computer + ender modem + monitor, a chunky turtle with ender modem roaming the world and doing some basic rednest broadcasting.

First time I restart the server and connect - stacktrace.

**Comment by Lupus590** [comment]
If you uninstall the mod that is providing the chunky turtle does the game still crash?

**Comment by SquidDev** [comment]
Closing in favour of #979, which appears to be the same issue.
