### ISSUE TITLE
Turtle placing refined storage disk drive crashes save and make it unplayable

### ISSUE THREAD

**Issue by VoidDave** [cc-tweaked/CC-Tweaked#1067]
### Minecraft Version

1.16.x

### Version

1.100.3

### Details

When turtle places disk drive anywhare on the word. save become unplayable.
logs:
[2022-04-10-17.log](https://github.com/cc-tweaked/CC-Tweaked/files/8458952/2022-04-10-17.log)

**Comment by SquidDev** [comment]
### Stack trace for convenience

```
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalStateException: No network node present at BlockPos{x=1487, y=66, z=-4415}, consider removing the block at this position
	at com.refinedmods.refinedstorage.tile.NetworkNodeTile.getNode(NetworkNodeTile.java:65) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.tile.NetworkNodeTile.getNode(NetworkNodeTile.java:24) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.block.NetworkNodeBlock.onDirectionChanged(NetworkNodeBlock.java:78) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.block.BaseBlock.checkIfDirectionHasChanged(BaseBlock.java:49) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.block.BaseBlock.func_196243_a(BaseBlock.java:42) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.block.NetworkNodeBlock.func_196243_a(NetworkNodeBlock.java:69) ~[refinedstorage:1.9.17]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196947_b(AbstractBlock.java:616) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:267) ~[?:?]
	at net.minecraft.world.World.func_241211_a_(World.java:199) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?]
	at net.minecraft.world.World.func_175656_a(World.java:283) ~[?:?]
	at com.refinedmods.refinedstorage.item.blockitem.BaseBlockItem.func_195941_b(BaseBlockItem.java:23) ~[refinedstorage:1.9.17]
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?]
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:651) ~[forge:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:186) ~[?:?]
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.doDeployOnBlock(TurtlePlaceCommand.java:286) ~[computercraft:1.100.3]
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deployOnBlock(TurtlePlaceCommand.java:242) ~[computercraft:1.100.3]
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deploy(TurtlePlaceCommand.java:122) ~[computercraft:1.100.3]
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.execute(TurtlePlaceCommand.java:79) ~[computercraft:1.100.3]
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:788) ~[computercraft:1.100.3]
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:133) ~[computercraft:1.100.3]
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:217) ~[computercraft:1.100.3]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
```


---

I'm afraid this is a vanilla bug, see https://github.com/cc-tweaked/CC-Tweaked/issues/691#issuecomment-766171581 - my understanding is that you can reproduce this with any "block placer" block entity.

Unfortunately this does mean there's nothing we can really do on our end, it really requires either a patch in Forge or individual mods to work around it themselves. It might be worth reporting this to the Refined Storage people too, to see if they're willing to do the latter.
