### ISSUE TITLE
NullPointerException when command computer places monitors

### ISSUE THREAD

**Issue by JadianRadiator** [cc-tweaked/CC-Tweaked#913]
### Minecraft Version

1.16.x

### Version

I've tried 1.16.5-1.98.2, 1.16.5-1.98.1, and 1.16.5-1.98.0

### Details

Weird graphical issue.
I've tried 1.16.5-1.98.2, 1.16.5-1.98.1, and 1.16.5-1.98.0
![Growth Chamger Bug_Issue](https://user-images.githubusercontent.com/43524862/131393891-c9fa206d-889b-46cf-92a1-796c440cc23e.png)
Here's the cf pack profile for mods installed.
[Dionysis.zip](https://github.com/SquidDev-CC/CC-Tweaked/files/7079097/Dionysis.zip)
And here are the logs.
https://gist.github.com/JadianRadiator/50371a73f2507a13ad787463c485ecdd

### Steps to Reproduce
Have the versions of Dynamic Trees and CC: Tweaked in the pack profile above,
and make a growth chamber following the instructions for it found [here](https://github.com/ferreusveritas/DynamicTrees/wiki/Growth-Chambers).

**Comment by SquidDev** [comment]
Hrmr, this is odd. I'd guess the problem here is that the command computer places monitors in an incomplete state, the new checks reject some monitors and allow others. Very odd.

A quick fix on your end would be to break all monitors and then replace them (as two separate steps). It's the automated placing and our handling of that which is borked.

---

Some notes for future me:
```
[14:07:55] [Render thread/INFO]: Loaded monitor shader.
[14:08:21] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.contract(TileMonitor.java:629) ~[?:1.98.0]
	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.contractNeighbours(TileMonitor.java:564) ~[?:1.98.0]
	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.destroy(TileMonitor.java:92) ~[?:1.98.0]
	at dan200.computercraft.shared.common.BlockGeneric.func_196243_a(BlockGeneric.java:46) ~[?:1.98.0]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196947_b(AbstractBlock.java:616) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:267) ~[?:?]
	at net.minecraft.world.World.func_241211_a_(World.java:199) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?]
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:214) ~[?:?]
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:245) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:149) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$6467/1902391167.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5976/1096402541.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Stack trace for future reference. Looks to be caused by 3a80b51a9fd0857b36185392d4f9a2f38a97155b / 96316cddaa213064adbc6deddda0d37a633d2ce1.

Looks like I'm going to have to rewrite this properly :D:.

**Comment by JadianRadiator** [comment]
I relogged the whole game/world, which fixed the display
