### ISSUE TITLE
[1.16.5] Crash upon world load on dedicated server

### ISSUE THREAD

**Issue by FoxMcloud5655** [cc-tweaked/CC-Tweaked#981]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

After the world is loaded, this error occurs on a dedicated server:
```
Caused by: java.lang.NoSuchMethodError: dan200.computercraft.api.peripheral.IPeripheral.getAdditionalTypes()Ljava/util/Set;
at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.<init>(PeripheralAPI.java:52) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.core.apis.PeripheralAPI.onPeripheralChanged(PeripheralAPI.java:234) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.core.computer.Environment.setPeripheral(Environment.java:317) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.shared.computer.core.ServerComputer.setPeripheral(ServerComputer.java:288) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.shared.computer.blocks.TileComputerBase.refreshPeripheral(TileComputerBase.java:252) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInputsImmediately(TileComputerBase.java:276) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:378) ~[computercraft:1.99.0] {re:classloading}
at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_73660_a(TileComputerBase.java:159) ~[computercraft:1.99.0] {re:classloading}
```
I am unsure if it's due to a Peripheral from an addon or not.  The crash report details no other mod in the stacktrace.

**Comment by SquidDev** [comment]
See #972. Supplementaries is bundling the CC:T API by mistake - upgrading to their latest version should fix things.
